editing mistakes
Chahlyk/home-accounting pull request #1
Opened 2022-03-16 10:37 UTC by Chahlyk

2022-03-16 11:26 UTC, Liliia-Abr requested changes

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/detail-event/detail-event.component.css
> +
у тебя нужно менять стили написания классов - зачем это? Если начала писать через дефис, то и продолжай через дефис, не нужно перескакивать на камелкейс

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/detail-event/detail-event.component.html
> +      <p [class]="colourType" class="type">{{event.type | titlecase}}</p>
тут я хотела увидеть использование ngClass

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/detail-event/detail-event.component.ts
> +          this.colourType = this.event.type === 'income' ? 'blueText' : 'redText';
почему бы не сделать 1 переменную которая будет отвечать за смену классов, а если у тебя будет 10 полей который меняют цвет в зависимости там true или false пришло - не будем же создавать 10 переменных для каждого поля отдельно?

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/detail-event/detail-event.component.ts
> +    const id = parseInt(this.route.snapshot.paramMap.get('id')!, 10);
а что за 10 в конце?

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/detail-event/detail-event.component.ts
> +  private getCategory(event: IEvents): string {
вот эти данны сохрани в сабжект после запроса в основном компоненте и тут их используй, чтоб не запрашивать снова или посмотри как можно передавать данный в ангуляре при переходах по роутерам (подскажу там всякие резолверы)

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/history.component.ts
> +
пустая строка

2022-03-16 11:26 UTC, Liliia-Abr commented on src/app/pages/history/history.component.ts
> +
при переборе не забывай интерфейсы прописывать

2022-03-16 14:30 UTC, Chahlyk commented on src/app/pages/history/detail-event/detail-event.component.ts
> +    const id = parseInt(this.route.snapshot.paramMap.get('id')!, 10);
радикс, обязательный параметр

2022-03-16 16:22 UTC, Liliia-Abr commented on src/app/pages/history/detail-event/detail-event.component.ts
> +    const id = parseInt(this.route.snapshot.paramMap.get('id')!, 10);
зачем тут parseInt?

2022-03-22 11:27 UTC, Liliia-Abr approved these changes

2022-03-22 12:26 UTC, merged